#include <iostream>
#include "funcs.h"

int main()
{
	std::string errorA = box(5, -1);
	std::cout << "\nbox(5, -1):\n";
	std::cout << errorA;
	std::cout << "\n------------------\n";
	std::string a1 = box(1, 1);
	std::cout << "\nbox(1,1):\n";
	std::cout << a1;
	std::cout << "\n------------------\n";
	std::string a2 = box(5, 3);
	std::cout << "\nbox(5, 3):\n";
	std::cout << a2;
	std::cout << "\n------------------\n";
	std::string a3 = box(7, 4);
	std::cout << "\nbox(7, 4):\n";
	std::cout << a3;
	std::cout << "\n------------------\n";

	std::string errorB = checkerboard(5, -1);
	std::cout << "\ncheckerboard(5, -1):\n";
	std::cout << errorB;
	std::cout << "\n------------------\n";
	std::string b1 = checkerboard(1, 1);
	std::cout << "\ncheckerboard(1, 1):\n";
	std::cout << b1;
	std::cout << "\n------------------\n";
	std::string b2 = checkerboard(5, 5);
	std::cout << "\ncheckerboard(5, 5):\n";
	std::cout << b2;
	std::cout << "\n------------------\n";
	std::string b3 = checkerboard(11,6);
	std::cout << "\ncheckerboard(11, 6):\n";
	std::cout << b3;
	std::cout << "\n------------------\n";
	
	std::string errorC = cross(-1);
	std::cout << "\ncross(-1):\n";
	std::cout << errorC;
	std::cout << "\n------------------\n";
	std::string c1 = cross(1);
	std::cout << "\ncross(1):\n";
	std::cout << c1;
	std::cout << "\n------------------\n";
	std::string c2 = cross(5);
	std::cout << "\ncross(5):\n";
	std::cout << c2;
	std::cout << "\n------------------\n";
	std::string c3 = cross(8);
	std::cout << "\ncross(8):\n";
	std::cout << c3;
	std::cout << "\n------------------\n";
	std::string c4 = cross(13);
	std::cout << "\ncross(13):\n";
	std::cout << c4;
	std::cout << "\n------------------\n";

	std::string errorD = lower(-1);
	std::cout << "\nlower(-1):\n";
	std::cout << errorD;
	std::cout << "\n------------------\n";
	std::string d1 = lower(1);
	std::cout << "\nlower(1):\n";
	std::cout << d1;
	std::cout << "\n------------------\n";
	std::string d2 = lower(4);
	std::cout << "\nlower(4):\n";
	std::cout << d2;
	std::cout << "\n------------------\n";
	std::string d3 = lower(6);
	std::cout << "\nlower(6):\n";
	std::cout << d3;
	std::cout << "\n------------------\n";

	std::string errorE = upper(-1);
	std::cout << "\nupper(-1):\n";
	std::cout << errorE;
	std::cout << "\n------------------\n";
	std::string e1 = upper(1);
	std::cout << "\nupper(1):\n";
	std::cout << e1;
	std::cout << "\n------------------\n";
	std::string e2 = upper(5);
	std::cout << "\nupper(5):\n";
	std::cout << e2;
	std::cout << "\n------------------\n";
	std::string e3 = upper(8);
	std::cout << "\nupper(8):\n";
	std::cout << e3;
	std::cout << "\n------------------\n";

	std::string errorF = trapezoid(1, -1);
	std::cout << "\ntrapezoid(1, -1):\n";
	std::cout << errorF;
	std::cout << "\n------------------\n";
	std::string f1 = trapezoid(2, 1);
	std::cout << "\ntrapezoid(2, 1):\n";
	std::cout << f1;
	std::cout << "\n------------------\n";
	std::string f2 = trapezoid(5, 2);
	std::cout << "\ntrapezoid(5, 2):\n";
	std::cout << f2;
	std::cout << "\n------------------\n";
	std::string f3 = trapezoid(5, 3);
	std::cout << "\ntrapezoid(5, 3):\n";
	std::cout << f3;
	std::cout << "\n------------------\n";
	std::string f4 = trapezoid(12, 5);
	std::cout << "\ntrapezoid(12, 5):\n";
	std::cout << f4;
	std::cout << "\n------------------\n";
	std::string f5 = trapezoid(12, 7);
	std::cout << "\ntrapezoid(12, 7):\n";
	std::cout << f5;
	std::cout << "\n------------------\n";
	
	std::string errorG = checker3x3(5, -1);
	std::cout << "\nchecker3x3(5, -1):\n";
	std::cout << errorG;
	std::cout << "\n------------------\n";
	std::string g1 = checker3x3(1, 1);
	std::cout << "\nchecker3x3(1, 1):\n";
	std::cout << g1;
	std::cout << "\n------------------\n";
	std::string g2 = checker3x3(5, 7);
	std::cout << "\nchecker3x3(5, 7):\n";
	std::cout << g2;
	std::cout << "\n------------------\n";
	std::string g3 = checker3x3(10,10);
	std::cout << "\nchecker3x3(10,10):\n";
	std::cout << g3;
	std::cout << "\n------------------\n";
	std::string g4 = checker3x3(16, 11);
	std::cout << "\nchecker3x3(16, 11):\n";
	std::cout << g4;
	std::cout << "\n------------------\n";
}